# Generated by Django 5.2.1 on 2025-05-12 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education_Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False, verbose_name='Активный')),
                ('started_at', models.DateField(verbose_name='Начало потока')),
                ('ended_at', models.DateField(verbose_name='Окончание потока')),
                ('articul', models.CharField(choices=[('regular', 'regular'), ('bootcamp', 'bootcamp'), ('workshop', 'workshop'), ('indi', 'indi')], verbose_name='Артикул потока')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.person')),
            ],
        ),
    ]
