# Generated by Django 5.2.1 on 2025-05-13 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education_thread',
            name='author',
        ),
    ]
