# Generated by Django 5.2.1 on 2025-05-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0002_remove_education_thread_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education_thread',
            name='status',
        ),
        migrations.AddField(
            model_name='education_thread',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название потока'),
        ),
        migrations.AddField(
            model_name='education_thread',
            name='type_course',
            field=models.CharField(blank=True, choices=[('regular', 'regular'), ('bootcamp', 'bootcamp'), ('workshop', 'workshop'), ('indi', 'indi')], max_length=20, verbose_name='Тип курса'),
        ),
        migrations.AlterField(
            model_name='education_thread',
            name='articul',
            field=models.CharField(blank=True, max_length=100, verbose_name='Артикул потока'),
        ),
    ]
