# Generated by Django 5.2.1 on 2025-05-13 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0003_remove_education_thread_status_education_thread_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education_thread',
            options={'verbose_name': 'Образовательный поток', 'verbose_name_plural': 'Образовательные потоки'},
        ),
        migrations.AlterField(
            model_name='education_thread',
            name='articul',
            field=models.CharField(blank=True, max_length=20, verbose_name='Артикул потока'),
        ),
    ]
