# Generated by Django 5.2.1 on 2025-05-13 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_remove_presenter_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accrual',
            options={'verbose_name': 'Начисление', 'verbose_name_plural': 'Начисления'},
        ),
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Авторский контракт', 'verbose_name_plural': 'Авторские контракты'},
        ),
        migrations.AlterModelOptions(
            name='presenter',
            options={'verbose_name': 'По часовой контракт', 'verbose_name_plural': 'По часовые контракты'},
        ),
        migrations.RemoveField(
            model_name='author',
            name='title',
        ),
    ]
