# Generated by Django 5.2.1 on 2025-05-13 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_alter_author_options_alter_presenter_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accrual',
            name='hours_worked',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Фактические часы'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_nunber',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Номер контракта'),
        ),
        migrations.AlterField(
            model_name='presenter',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=1, max_digits=8, verbose_name='Ставка за час'),
        ),
    ]
