# Generated by Django 5.2.1 on 2025-05-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_alter_accrual_hours_worked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presenter',
            name='estimate',
            field=models.DecimalField(decimal_places=1, max_digits=8, verbose_name='Прогнозное кол-во часов'),
        ),
    ]
