# Generated by Django 5.2.1 on 2025-05-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_alter_presenter_estimate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accrual',
            name='hours_worked',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Фактические часы'),
        ),
        migrations.AlterField(
            model_name='author',
            name='revenue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, verbose_name='Ожидаемый оборот/прибыль'),
        ),
    ]
