# Generated by Django 5.2.1 on 2025-05-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0007_alter_accrual_hours_worked_alter_author_revenue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accrual',
            name='accrual_flags',
            field=models.CharField(choices=[('collapsed', 'Схлопнутое'), ('correction', 'Корректировка'), ('non_financial', 'Нефинансовое')], default='-------'),
        ),
        migrations.AlterField(
            model_name='author',
            name='revenue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, verbose_name='Ожидаемый оборот/прибыль'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='comment_manager',
            field=models.TextField(blank=True, verbose_name='Комментарий менеджера'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='created_at',
            field=models.DateField(auto_created=True, verbose_name='Дата создание'),
        ),
    ]
