# Generated by Django 5.2.1 on 2025-05-13 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0008_alter_accrual_accrual_flags_alter_author_revenue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создание'),
        ),
        migrations.AlterUniqueTogether(
            name='contract',
            unique_together={('contract_nunber',)},
        ),
    ]
