# Generated by Django 5.2.1 on 2025-05-13 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_manager_options_alter_person_options_and_more'),
        ('contracts', '0010_rename_contract_nunber_contract_contract_number_and_more'),
        ('threads', '0004_alter_education_thread_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accrual',
            name='accrual_flags',
            field=models.CharField(blank=True, choices=[('collapsed', 'Схлопнутое'), ('correction', 'Корректировка'), ('non_financial', 'Нефинансовое')], default=None),
        ),
        migrations.AlterField(
            model_name='accrual',
            name='accrual_status',
            field=models.CharField(blank=True, choices=[('pending', 'Ожидание'), ('verified', 'Проверено')], default='pending'),
        ),
        migrations.AlterField(
            model_name='accrual',
            name='created_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.manager', verbose_name='Кто завел начисление'),
        ),
        migrations.AlterField(
            model_name='accrual',
            name='hours_worked',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Проставлять факт. часов при выборе контракта Ведущий', max_digits=5, null=True, verbose_name='Фактические часы'),
        ),
        migrations.AlterField(
            model_name='accrual',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_accruals', to='accounts.manager', verbose_name='Кто изменил начисление'),
        ),
        migrations.AlterField(
            model_name='author',
            name='thead',
            field=models.ManyToManyField(blank=True, related_name='author_theads', to='threads.education_thread'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='responsible_manager',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsible_contracts', to='accounts.manager', verbose_name='Ответственный сотрудник'),
        ),
        migrations.AlterField(
            model_name='presenter',
            name='thead',
            field=models.ManyToManyField(blank=True, related_name='presenter_theads', to='threads.education_thread'),
        ),
    ]
