# Generated by Django 5.2.1 on 2025-05-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0011_alter_accrual_accrual_flags_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ['contract_number'], 'verbose_name': 'Контракт', 'verbose_name_plural': 'Контракты'},
        ),
        migrations.AddField(
            model_name='accrual',
            name='real_revenue',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Проставлять факт. при выборе контракта Авторский', max_digits=10, null=True, verbose_name='Фактический оборот/выручка'),
        ),
    ]
