# Generated by Django 5.2.1 on 2025-05-13 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_manager_options_alter_person_options_and_more'),
        ('contracts', '0012_alter_contract_options_accrual_real_revenue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='responsible_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsible_contracts', to='accounts.manager', verbose_name='Ответственный сотрудник'),
        ),
    ]
