# Generated by Django 5.2.1 on 2025-05-14 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0015_alter_contract_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accrual',
            name='contract_type',
            field=models.CharField(blank=True, choices=[('author', 'Авторский'), ('presenter', 'Ведущий'), ('combined', 'Смешаный')], max_length=20, null=True, verbose_name='Тип контракта'),
        ),
    ]
