# Generated by Django 5.2.1 on 2025-05-14 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0016_alter_accrual_contract_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='reward_type',
            field=models.CharField(choices=[('Оборот', 'Оборот'), ('Прибыль', 'Прибыль')], default='Оборот', verbose_name='Тип награды'),
        ),
    ]
