# Generated by Django 5.2.1 on 2025-05-14 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0017_alter_author_reward_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accrual',
            name='contract_type',
        ),
    ]
