# Generated by Django 5.2.1 on 2025-05-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, verbose_name='Пользователь')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('contact_phone', models.CharField(blank=True, null=True)),
                ('manager', models.CharField(verbose_name='Менеджер')),
            ],
        ),
    ]
