# Generated by Django 5.2.1 on 2025-05-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager', models.CharField(verbose_name='Менеджер')),
            ],
        ),
        migrations.RemoveField(
            model_name='person',
            name='manager',
        ),
    ]
