# Generated by Django 5.2.1 on 2025-05-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_manager_remove_person_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='manager',
            field=models.CharField(blank=True, null=True, verbose_name='Менеджер'),
        ),
        migrations.AlterField(
            model_name='person',
            name='username',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Пользователь'),
        ),
    ]
