# Generated by Django 5.2.1 on 2025-05-13 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_manager_manager_alter_person_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manager',
            options={'verbose_name': 'Менеджер', 'verbose_name_plural': 'Менеджеры'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Преподаватель', 'verbose_name_plural': 'Преподаватели'},
        ),
        migrations.AlterField(
            model_name='manager',
            name='manager',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Менеджер'),
        ),
        migrations.AlterField(
            model_name='person',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='контактный email'),
        ),
        migrations.AlterField(
            model_name='person',
            name='contact_phone',
            field=models.CharField(blank=True, null=True, verbose_name='контактный тел.'),
        ),
    ]
